[package]
publish = false
name = "java-ext-wasm"
version = "0.1.0"
authors = ["Ivan Enderlin <ivan.enderlin@hoa-project.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmer-runtime = "0.11"
wasmer-runtime-core = "0.11"
jni = "0.14"
